# Permalinks
permalink:        pretty

# Setup
title:            INDS-Inc
tagline:          Integrated Nonclinical Development Solutions, Inc.
description:      Integrated Nonclinical Development Solutions, Inc. Creative and effective drug development/toxicology consultants & developers of SEND Explorer®
url:              http://inds-inc.com
baseurl:          '/'
paginate:         10
paginate_path:    /news/page:num/
logo:             /assets/images/inds_logo.png
author:           INDS Inc.

author:
  name:           INDS Inc.
  location:       Ann Arbor, MI  USA
  email:          joyce.zandee@inds-inc.com
  twitter:        INDSinc

twitter:
  username:       INDSinc

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

version:          '1.0.0'

github:
  repo:           'https://github.com/inds-inc/inds-inc.github.io'

sass:
    style:        ':compressed'